name: job-dependent

on: [push]

jobs:
    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: STEP A
          run: echo "world"
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: step b
          run: echo "hello"



