name: "Dep Jobs Example"

on: ['push']

jobs:
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: stepA
        run: echo "World"
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        run: echo "Hello"